package com._6.group4.smartcart.instacart;

import com._6.group4.smartcart.grocery.GroceryAggregationService;
import com._6.group4.smartcart.grocery.PantryItem;
import com._6.group4.smartcart.grocery.PantryItemRepository;
import com._6.group4.smartcart.mealplanning.MealPlan;
import com._6.group4.smartcart.mealplanning.MealPlanRepository;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.NoSuchElementException;

@Service
public class InstacartShoppingListService {

    private static final DateTimeFormatter WEEK_LABEL = DateTimeFormatter.ISO_LOCAL_DATE;

    private final MealPlanRepository mealPlanRepository;
    private final PantryItemRepository pantryItemRepository;
    private final GroceryAggregationService groceryAggregationService;
    private final InstacartGateway instacartGateway;
    private final String partnerLinkbackUrl;
    private final Integer expiresInDays;

    public InstacartShoppingListService(MealPlanRepository mealPlanRepository,
                                        PantryItemRepository pantryItemRepository,
                                        GroceryAggregationService groceryAggregationService,
                                        InstacartGateway instacartGateway,
                                        @Value("${instacart.partner-linkback-url:}") String partnerLinkbackUrl,
                                        @Value("${instacart.shopping-list.expires-in-days:14}") Integer expiresInDays) {
        this.mealPlanRepository = mealPlanRepository;
        this.pantryItemRepository = pantryItemRepository;
        this.groceryAggregationService = groceryAggregationService;
        this.instacartGateway = instacartGateway;
        this.partnerLinkbackUrl = partnerLinkbackUrl != null ? partnerLinkbackUrl.trim() : "";
        this.expiresInDays = expiresInDays != null && expiresInDays > 0 ? expiresInDays : null;
    }

    @Transactional(readOnly = true)
    public ShoppingListLinkResult createShoppingListLinkForUser(Long userId) {
        MealPlan latestPlan = mealPlanRepository.findTopByUserIdOrderByCreatedAtDesc(userId)
                .orElseThrow(() -> new NoSuchElementException("Generate a meal plan before sending items to Instacart."));
        List<PantryItem> pantryItems = pantryItemRepository.findAllByUserIdOrderByIngredientName(userId);
        GroceryAggregationService.GroceryListResponse groceryList =
                groceryAggregationService.buildGroceryList(latestPlan, pantryItems);

        if (groceryList.items().isEmpty()) {
            throw new IllegalArgumentException("There are no remaining grocery items to send to Instacart.");
        }

        List<LineItem> lineItems = buildLineItems(groceryList.items());
        if (lineItems.isEmpty()) {
            throw new IllegalArgumentException("SmartCart could not build a valid Instacart shopping list from the remaining items.");
        }

        String title = "SmartCart Grocery List";
        if (latestPlan.getWeekStartDate() != null) {
            title += " - Week of " + WEEK_LABEL.format(latestPlan.getWeekStartDate());
        }

        ProductsLinkRequest request = new ProductsLinkRequest(
                title,
                "shopping_list",
                expiresInDays,
                buildInstructions(groceryList),
                lineItems,
                buildLandingPageConfiguration()
        );

        ProductsLinkResponse response = instacartGateway.createProductsLink(request);
        if (response == null || response.productsLinkUrl() == null || response.productsLinkUrl().isBlank()) {
            throw new InstacartGatewayException("Instacart did not return a shopping list URL.");
        }

        return new ShoppingListLinkResult(response.productsLinkUrl(), lineItems.size(), title);
    }

    private List<String> buildInstructions(GroceryAggregationService.GroceryListResponse groceryList) {
        List<String> instructions = new ArrayList<>();
        instructions.add("Generated by SmartCart from your weekly meal plan.");
        instructions.add("Line items include only the ingredients and quantities you still need to buy.");
        if (groceryList.pantrySubtractedCount() > 0) {
            instructions.add("SmartCart removed items already covered by pantry quantities before sending this list.");
        }
        return instructions;
    }

    private LandingPageConfiguration buildLandingPageConfiguration() {
        if (partnerLinkbackUrl.isBlank()) {
            return null;
        }
        return new LandingPageConfiguration(partnerLinkbackUrl);
    }

    private List<LineItem> buildLineItems(List<GroceryAggregationService.GroceryListItemView> items) {
        List<LineItem> lineItems = new ArrayList<>();
        for (GroceryAggregationService.GroceryListItemView item : items) {
            String name = sanitizeName(item.name());
            if (name == null) {
                continue;
            }

            String supportedUnit = toInstacartUnit(item.unit());
            Double supportedQuantity = toInstacartQuantity(item.quantityValue(), supportedUnit);
            String displayText = buildDisplayText(item);

            lineItems.add(new LineItem(name, supportedQuantity, supportedUnit, displayText));
        }
        return lineItems;
    }

    private String sanitizeName(String name) {
        if (name == null) {
            return null;
        }
        String trimmed = name.trim();
        return trimmed.isBlank() ? null : trimmed;
    }

    private String buildDisplayText(GroceryAggregationService.GroceryListItemView item) {
        String name = sanitizeName(item.name());
        String quantity = item.quantity();
        if (name == null) {
            return null;
        }
        if (quantity == null || quantity.isBlank()) {
            return name;
        }
        return quantity + " " + name;
    }

    private Double toInstacartQuantity(Double quantityValue, String supportedUnit) {
        if (quantityValue == null || supportedUnit == null || quantityValue <= 0d) {
            return null;
        }
        return BigDecimal.valueOf(quantityValue)
                .setScale(3, RoundingMode.HALF_UP)
                .stripTrailingZeros()
                .doubleValue();
    }

    static String toInstacartUnit(String unit) {
        if (unit == null || unit.isBlank()) {
            return null;
        }
        return switch (unit.trim().toLowerCase(Locale.ROOT)) {
            case "count", "each" -> "each";
            case "cup" -> "cup";
            case "tbsp" -> "tablespoon";
            case "tsp" -> "teaspoon";
            case "ml" -> "milliliter";
            case "l" -> "liter";
            case "oz" -> "ounce";
            case "lb" -> "pound";
            case "g" -> "gram";
            case "kg" -> "kilogram";
            case "fl oz" -> "fl oz";
            case "can" -> "can";
            case "bunch" -> "bunch";
            case "head" -> "head";
            case "package" -> "package";
            case "packet" -> "packet";
            case "small" -> "small";
            case "medium" -> "medium";
            case "large" -> "large";
            default -> null;
        };
    }

    public record ShoppingListLinkResult(
            String productsLinkUrl,
            int itemCount,
            String title
    ) {
    }

    @JsonInclude(JsonInclude.Include.NON_NULL)
    public record ProductsLinkRequest(
            String title,
            String linkType,
            Integer expiresIn,
            List<String> instructions,
            List<LineItem> lineItems,
            LandingPageConfiguration landingPageConfiguration
    ) {
        public Map<String, Object> toApiBody() {
            Map<String, Object> body = new LinkedHashMap<>();
            body.put("title", title);
            body.put("link_type", linkType);
            if (expiresIn != null) {
                body.put("expires_in", expiresIn);
            }
            if (instructions != null && !instructions.isEmpty()) {
                body.put("instructions", instructions);
            }

            List<Map<String, Object>> serializedLineItems = new ArrayList<>();
            for (LineItem lineItem : lineItems) {
                serializedLineItems.add(lineItem.toApiBody());
            }
            body.put("line_items", serializedLineItems);

            if (landingPageConfiguration != null) {
                body.put("landing_page_configuration", landingPageConfiguration.toApiBody());
            }
            return body;
        }
    }

    @JsonInclude(JsonInclude.Include.NON_NULL)
    public record LineItem(
            String name,
            Double quantity,
            String unit,
            String displayText
    ) {
        Map<String, Object> toApiBody() {
            Map<String, Object> body = new LinkedHashMap<>();
            body.put("name", name);
            if (quantity != null) {
                body.put("quantity", quantity);
            }
            if (unit != null) {
                body.put("unit", unit);
            }
            if (displayText != null && !displayText.isBlank()) {
                body.put("display_text", displayText);
            }
            return body;
        }
    }

    @JsonInclude(JsonInclude.Include.NON_NULL)
    public record LandingPageConfiguration(String partnerLinkbackUrl) {
        Map<String, Object> toApiBody() {
            return Map.of("partner_linkback_url", partnerLinkbackUrl);
        }
    }

    public record ProductsLinkResponse(@JsonProperty("products_link_url") String productsLinkUrl) {
    }
}
